apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-ellington-web
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/siege-analytics/ellington-web-manifests
    targetRevision: main
    path: base
  destination:
    server: https://kubernetes.default.svc
    namespace: ellington
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
